### ISSUE TITLE
Model availability from models trained in preprint

### ISSUE THREAD

**Issue by taylorreiter** [IBM/AutoPeptideML#6]
Hello, I recently read your preprint, "[AutoPeptideML: Automated Machine Learning for Building Trustworthy Peptide Bioactivity Predictors](https://www.biorxiv.org/content/10.1101/2023.11.13.566825v1)." I was curious if you would be willing to provide the models you trained in the paper. I apologize if they are available and I missed them.

**Comment by RaulFD-creator** [comment]
Hi @taylorreiter, yes I am trying to figure a way to upload all of them in a permanent repository, because a lot of experiments were run, the whole collection occupies a lot of space. In the meantime, I could send you a specific batch of models for example, one of the three replicates used in Fig 2. for the AutoPeptideML training + NegSearch + HP series. Let me know if that would be helpful (and what batch(es) of models would you be interested in). Otherwise, for the whole collection it may take a bit more time.

**Comment by taylorreiter** [comment]
Hi @RaulFD-creator. Thank you, a specific batch of models would be wonderful! Whichever set of models you would recommend using for a biological use case (I assume AutoPeptideML + NegSearch + HP) would be most helpful to me. My email is taylorreiter at gmail dot com.

As for locations to upload, have considered either zenodo or OSF? Zenodo allows up to 50gb per repository. OSF allows 5gb of native storage, but allows you to link to external storage databases (google drive, etc) which then extends the storage to whatever the capacity of the linked database is. Sorry if these suggestions aren't helpful!

**Comment by RaulFD-creator** [comment]
I didn't know about OSF, I was looking at Zenodo. I'll check it out and try to see which one is best. Thanks for the suggestion! I have sent the models to your email. Hope you find them useful.

**Comment by RaulFD-creator** [comment]
We have just released a new tab in the webserver to use the predictors trained for the experiments described in the paper (OMLE+NegSearch+HP). Updates on the Zenodo will arrive when the paper gets through the review process and there are no further experiments to include.

**Comment by RaulFD-creator** [comment]
Hi, with the publication of the [paper](https://doi.org/10.1093/bioinformatics/btae555), we have made the models finally available through [Zenodo](https://zenodo.org/records/13363975/files/AutoPeptideML_SI.tar.gz?download=1).
